### ISSUE TITLE
How to get JWT in check_resource

### ISSUE THREAD

**Issue by codingquark** [rabbitmq/rabbitmq-auth-backend-amqp#22]
Hello!

I am using this plugin with JWT as password. I checked headers, props and body in each of the cases (login, check_vhost, check_resource, check_topic) and it seems that the password (which is JWT in this case) is passed _only_ for `login` action.

Is there anyway I can get the JWT (the password) in the rest of the actions as well?

My intention is to parse the claims and decide if the user is allowed to access certain resources. Is there an alternative approach you would suggest for this?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The password isn't passed for the rest of the authN/authZ API in 3.7.x. In master it is, otherwise [rabbitmq-auth-backend-oauth2](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2) wouldn't be possible.

There is no workaround. We have considered backporting the change but it's technically breaking for plugin authors so some team members are uncomfortable with that.
